### ISSUE TITLE
[feat] ox_esx using ox_inventory notify

### ISSUE THREAD

**Issue by MrNewb** [overextended/es_extended#11]
Suggesting on the ox_extended to swap all notifications to use the system in ox_inventoryhud, possibly enabled by the config to use defualt/ox_notify

**Comment by thelindat** [comment]
I'm accepting PRs and fixing bugs, but not implementing anything (especially when the plan is to move away from ESX in the future).

This would cause issues when moving non-essential UI elements to another resource, too.
