### ISSUE TITLE
[Bug] ESX.OneSync.Players broken

### ISSUE THREAD

**Issue by benzon** [overextended/es_extended#19]
So there is multiple issues with this function.

Ill do a PR. ad some point.

Line 7 - GetEntityCoords(GetPlayerPed(coords)) - This statement is wrong using coords in GetPlayerPed.

Line 11 - if closest ~= nil then - will always give you the wrong result wont even check distance, this line will stop the function from even doing what it should.

Line 22 - if dist <= players.distance or distance then - players.distance is never set so should even check this, unless the function checks the same player twice ?

https://github.com/overextended/es_extended/blob/b3b5ffa218189e1720353c34390d03ac0388be87/server/onesync.lua#L3

**Comment by thelindat** [comment]
I wrote this stuff ages ago for QRP and never did in-depth testing because we stopped immediately after.
Some of the values are off, but not the ones you think (based on the intent when I wrote it). I'm fine with rewriting it though.


```lua
---@param source vector|number coords or source entity
---@param closest boolean only return the closest player
---@param distance number distance to check
---@param ignore table players to ignore
---@return table
function ESX.OneSync.Players(source, closest, distance, ignore)
	local result = {}
	local count = 0
	if not distance then distance = 100 end
	if type(source) == 'number' then source = GetEntityCoords(source) end

	for _, xPlayer in pairs(ESX.Players) do
		if not ignore or not ignore[xPlayer.source] then
			local entity = GetPlayerPed(xPlayer.source)
			local coords = GetEntityCoords(entity)

			if not closest then
				local dist = #(source - coords)
				if dist <= distance then
					count += 1
					result[count] = {id = xPlayer.source, ped = entity, coords = coords, dist = dist}
				end
			else
				local dist = #(source - coords)
				if dist <= (result.distance or distance) then
					result = {id = xPlayer.source, ped = entity, coords = coords, dist = dist}
				end
			end
		end
	end

	return result
end


print(json.encode(
	ESX.OneSync.Players(GetPlayerPed(1), true, 2, {1})
))
```

**Comment by benzon** [comment]
It was not to bash any one just realised some issues with it.

Okay you got a line that i dont understand fully.

if dist <= (result.distance or distance) then

Where dos result.distance come from, since the result array would not have anything just caled result.dstance from what i can see.

And ignore, is that just to ignore specific persons or how?

**Comment by thelindat** [comment]
If result.distance is undefined, it will instead check distance.
Ignore is an array of playerIds to skip.

**Comment by thelindat** [comment]
I've pushed the updated Player functions; if there's any issues with the others just PR, it isn't something I want to work on right now.
