### ISSUE TITLE
NPWD version of es_extended make high MS at NPWD

### ISSUE THREAD

**Issue by Velkostatkar** [overextended/es_extended#21]
Hello,

thanks for your job. I really dont want make a enemy here.

But :-)

this version bring NPWD into astronomical MS

without this es_extend
phone take 0,01 - 0,04 MS

With this version od es_extended
phone take  0,40 - 0,60MS

worst is that, this version afecting the NPWD even if you false multichar and false NWPD config in es_extended
but in this situation phone take about 0,20MS

Sry for this info.

**Comment by thelindat** [comment]
This doesn't do anything to NPWD, just triggers the register events.
