### ISSUE TITLE
GetVehicleInDirection

### ISSUE THREAD

**Issue by DogsGoBark** [overextended/es_extended#27]
**Server Details:**
Windows

**Artifact:**
5123

**Issues:**
Not sure what I am doing wrong but there is nothing returning back even though you're staring at the vehicle in front of you. If this is the wrong way then let me know.

https://github.com/overextended/es_extended/blob/997a4a14e5c234c02bc86225599bb538d10aad57/client/functions.lua#L518-L534

```lua
RegisterCommand('testkey', function()
    local vehicle = ESX.Game.GetVehicleInDirection()
    local plate = GetVehicleNumberPlateText(vehicle)
    print(vehicle, plate)
end)
```

However, something like this works fine?
```lua
RegisterCommand('testkey', function()
    local playerCoords = GetEntityCoords(PlayerPedId())
    local vehicle, vehicleDistance = ESX.Game.GetClosestVehicle(playerCoords)
    local vehicleCoords = GetEntityCoords(vehicle)

    if #(playerCoords - vehicleCoords) > 3 then return end
    local plate = GetVehicleNumberPlateText(vehicle)

    print(vehicle, plate)
end)
```

**Comment by thelindat** [comment]
I reverted some code from a while back, so if it's not working now /shrug
