### ISSUE TITLE
Loadout

### ISSUE THREAD

**Issue by hichay** [overextended/es_extended#28]
This missing loadout system ?. im using old weapon type but seem it not load the loadout weapon anymore

**Comment by thelindat** [comment]
![image](https://user-images.githubusercontent.com/65407488/147398808-923ea668-096c-46f8-bf13-47debf7f7266.png)
![image](https://user-images.githubusercontent.com/65407488/147398810-d71091d2-c672-413c-939a-d4f5abc74655.png)
![image](https://user-images.githubusercontent.com/65407488/147398814-838a78f6-b1e3-45a2-be41-86a2fabecf6c.png)

I wonder.
