### ISSUE TITLE
saving players

### ISSUE THREAD

**Issue by makhmus** [overextended/es_extended#34]
hello, i just want to say its amazing what you guys are doing. Thank you for your work. I am having an issue where my characters dont spawn in at the last location they were at after quitting game and coming back they spawn in at the job center. is there a fix for this or something i missed during install, please let me know thank a bunch.

**Comment by thelindat** [comment]
It's not something I can reproduce 🤷

**Comment by PsychoShock** [comment]
You modify something for sure, make sure to not touch at player spawn.
