### ISSUE TITLE
high MS when saving

### ISSUE THREAD

**Issue by xrtw** [overextended/es_extended#35]
hello, currently having high MS when saving players. before with linden's es_extended version everything was good.
https://i.gyazo.com/cc7fc2239d7fff29e6a55f4aec3f875d.png

**Comment by dunak-debug** [comment]
How can be 300ms high ?

**Comment by xrtw** [comment]
> How can be 300ms high ?

sorry so thats not high?

**Comment by dunak-debug** [comment]
It is 0.3s, like your blink duration 😅 What was the time before using ox esx?

**Comment by xrtw** [comment]
> It is 0.3s, like your blink duration 😅 What was the time before using ox esx?

well it was written all the time 0.0 ms :D so idk

**Comment by frazz1234** [comment]
Yes me to lit trouble whit that ! Bit machine I try and same shit

**Comment by dolutattoo** [comment]
Guys, if it says 0.0ms when saving player then the timer is broken. Even for 1 player.
