### ISSUE TITLE
load jobs issue 

### ISSUE THREAD

**Issue by AamiRobin** [overextended/es_extended#37]
i am having some issues with loadjos. Sometimes after server restart, I need put command loadjobs to fix it. I think it just needs to execute this function after a few seconds.

**Comment by frazz1234** [comment]
Yes me to and a long query execution

**Comment by thelindat** [comment]
I never even finished the code for hot-reloading jobs, nor will I. If the function somehow isn't working at startup, you're probably loading a bunch of assets _after_ resources.

**Comment by AamiRobin** [comment]
It only happened if the server is under power and takes more than 30s to start. so most if the time I need to type "loadjobs" in the server console so the player can join.
