### ISSUE TITLE
SetInterval ID's Bug

### ISSUE THREAD

**Issue by benzon** [overextended/es_extended#4]
So just had some issues when i changed paychecks to be every minute i actually did not get payed more then once, after this the SetInterval died out, when i changed the SetInterval ID it works like expected, there might be an issue with SetInterval ID's

**Comment by thelindat** [comment]
Whoops, I had two intervals on the same ids.
I've updated the interval code anyway so they have their id's assigned at creation.

**Comment by benzon** [comment]
Super :) there was quite a few id's that where stacked hehe :D

**Comment by thelindat** [comment]
> 
> 
> Super :) there was quite a few id's that where stacked hehe :D

Was only paycheck and save intervals
