### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by BalloutJay** [overextended/es_extended#44]
I have a awaiting script and i think this is the problem but i cannot find it.
![Screenshot 2022-01-28 222156](https://user-images.githubusercontent.com/98054918/151645672-84ede4b5-0168-4872-b9dd-bbb2546386d9.png)

**Comment by fleevo32** [comment]
Update to the latest of both resources. Also start `oxmysql` before `es_extended` in your server.cfg. @BalloutJay

**Comment by BalloutJay** [comment]
> Update to the latest of both resources. Also start `oxmysql` before `es_extended` in your server.cfg. @BalloutJay

thanks you imma try this rn

**Comment by VIRUXE** [comment]
You must either compile the source or use the release.
