### ISSUE TITLE
Duplicated objects

### ISSUE THREAD

**Issue by lasitosPT** [overextended/es_extended#46]
Whenever i try to set new coords for an object with (SetEntityCoords), the object gets duplicated instead of only changing from one place to another
here is a video: https://streamable.com/6ls8lf

**Comment by VIRUXE** [comment]
Isto não tem nada a ver com esx.

This has nothing to do with es_extended.

**Comment by thelindat** [comment]
As I said on discord, and as above, ESX doesn't change how a _native function_ works.
